// <auto-generated />
using System;
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(GotchaFeedContext))]
    [Migration("20240527185422_SeedAll")]
    partial class SeedAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Gotcha.Entity.GotchaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepostQnt")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Gotcha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d266314f-31c4-4421-8623-17468424fea2"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2077),
                            RepostQnt = 10,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("af6b344a-bf4c-44eb-94b7-754a2b4ed71a"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2085),
                            RepostQnt = 20,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("d436694b-2fc8-495e-9f23-1eeba70f6d70"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2088),
                            RepostQnt = 10,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("e91861f2-4f1b-4759-8cd2-67fdb15049fb"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2091),
                            RepostQnt = 15,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("691d3a33-66ec-45e7-8c11-85cc28be380b"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2094),
                            RepostQnt = 25,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("f3ef7ea9-ad0e-4d5f-a417-da4b4a4edcec"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2103),
                            RepostQnt = 10,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("f12b1436-deb1-4d48-8a9b-7e3baafbb000"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2104),
                            RepostQnt = 20,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("941ee39a-1fb6-4740-adeb-06b4674353b7"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2106),
                            RepostQnt = 10,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("73f80851-4179-4d57-ab10-411a343cb47c"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2108),
                            RepostQnt = 15,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("58039889-aad1-46c2-9629-2712dfb7a06f"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2112),
                            RepostQnt = 25,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("f7ddac1c-7308-4e24-8af5-5f60c7a212ab"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2114),
                            RepostQnt = 10,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("66e74488-264e-441c-8fbc-89ff91add7fb"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2116),
                            RepostQnt = 20,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("bd380514-1bef-41a6-84c5-d60a59a934b3"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2118),
                            RepostQnt = 10,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("ff23f696-7d00-49a9-b862-2a8b9ccb8fa6"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2121),
                            RepostQnt = 15,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("b8e06c8e-8b3b-4b44-89fe-a65dbcff4a59"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2123),
                            RepostQnt = 25,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("c4f092b8-e38d-498e-9ebb-bd1132fbb5a0"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2125),
                            RepostQnt = 10,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("2043a6e8-8fee-455f-b051-a91302e83199"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2127),
                            RepostQnt = 20,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("fd9f73d1-02e8-4821-9bbb-4fba31df02e3"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(2131),
                            RepostQnt = 10,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("2868e482-3269-4e3e-87de-182f2ccf9549"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2133),
                            RepostQnt = 15,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("8e9b1587-08dd-46f5-b1e6-37acf2af36b9"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(2135),
                            RepostQnt = 25,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        });
                });

            modelBuilder.Entity("Domain.Gotcha.Repost.Entity.RepostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RepostDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Repost");
                });

            modelBuilder.Entity("Domain.Users.Entity.UsersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostsDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354"),
                            Active = true,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2022, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1900),
                            Email = "john.doe@example.com",
                            ImgBase64 = "6cdf691d-db36-4f9d-b567-2173d8431354.jpg",
                            LastAccessDate = new DateTime(2024, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1925),
                            LastName = "Doe",
                            Name = "John",
                            Nickname = "johnny",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f"),
                            Active = true,
                            BirthDate = new DateTime(1985, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1940),
                            Email = "jane.smith@example.com",
                            ImgBase64 = "fba74d07-310a-4e3a-b689-bb129fbe566f.jpg",
                            LastAccessDate = new DateTime(2024, 5, 26, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1941),
                            LastName = "Smith",
                            Name = "Jane",
                            Nickname = "janeS",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c"),
                            Active = true,
                            BirthDate = new DateTime(1992, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 11, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1951),
                            Email = "alice.johnson@example.com",
                            ImgBase64 = "0e3ee3ef-a250-436b-bae6-754e2685b18c.jpg",
                            LastAccessDate = new DateTime(2024, 4, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1955),
                            LastName = "Johnson",
                            Name = "Alice",
                            Nickname = "aliceJ",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29"),
                            Active = true,
                            BirthDate = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2021, 5, 27, 15, 54, 21, 716, DateTimeKind.Local).AddTicks(1965),
                            Email = "bob.brown@example.com",
                            ImgBase64 = "b09a4ec4-0cea-45fb-b992-a94208837d29.jpg",
                            LastAccessDate = new DateTime(2024, 5, 27, 10, 54, 21, 716, DateTimeKind.Local).AddTicks(1966),
                            LastName = "Brown",
                            Name = "Bob",
                            Nickname = "bobby",
                            PostsDay = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
