// <auto-generated />
using System;
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(GotchaFeedContext))]
    [Migration("20240527203651_NewRefer")]
    partial class NewRefer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Gotcha.Entity.GotchaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepostQnt")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Gotcha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98687f30-e119-4463-a306-e7e2fe9df544"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3403),
                            RepostQnt = 0,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("1fb63c07-c689-4096-871b-a7940f9e3d7a"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3408),
                            RepostQnt = 0,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("961f45f0-f5f9-4915-b32e-f6778862985d"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3413),
                            RepostQnt = 0,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("fd1537ba-61ee-42c2-9284-d2012b844750"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3415),
                            RepostQnt = 0,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("2bc444d1-4a52-4fbf-8208-3e1b9785ed05"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3418),
                            RepostQnt = 0,
                            UserId = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354")
                        },
                        new
                        {
                            Id = new Guid("9dc2afad-c7c5-43c9-b9ed-ae0fe6aee3c2"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3423),
                            RepostQnt = 0,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("518e3e45-fbc3-4c0d-9a6c-8a9dc8c4ac1c"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3427),
                            RepostQnt = 0,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("73a9a8db-cd15-476b-af61-854c35bbbf92"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3428),
                            RepostQnt = 0,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("976e0afd-beb4-4ccc-8952-e9b068ebffb1"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3430),
                            RepostQnt = 0,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("38cf2ad4-30ac-46e2-9240-ca3e82250002"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3433),
                            RepostQnt = 0,
                            UserId = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f")
                        },
                        new
                        {
                            Id = new Guid("638c2a44-f6e4-41ef-8136-4dbecbfd4472"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3437),
                            RepostQnt = 0,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("3b0303f0-ff85-4dd2-bd16-6cccea758914"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3438),
                            RepostQnt = 0,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("2a69ff19-f466-4c9b-8a2c-b8f5080b6208"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3440),
                            RepostQnt = 0,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("3f309c24-fa8c-4a73-9cd5-67348ce43bc1"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3442),
                            RepostQnt = 0,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("52098a53-8925-42f0-be7d-95c40c7599fb"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3445),
                            RepostQnt = 0,
                            UserId = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c")
                        },
                        new
                        {
                            Id = new Guid("45a65064-ca61-4134-b1eb-790cffe074d0"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3447),
                            RepostQnt = 0,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("b8bf6c5f-c110-459e-a80c-54325897efc7"),
                            Content = "Another interesting gotcha!",
                            CreationDate = new DateTime(2024, 5, 25, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3449),
                            RepostQnt = 0,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("8d08cf02-f060-410d-8ad6-9b9e4e75b6ff"),
                            Content = "This is the first gotcha content.",
                            CreationDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3451),
                            RepostQnt = 0,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("32816f48-9944-4a86-b991-a5b529454e2e"),
                            Content = "Yet another gotcha post for you.",
                            CreationDate = new DateTime(2024, 4, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3455),
                            RepostQnt = 0,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        },
                        new
                        {
                            Id = new Guid("b703c185-b4ee-4f6c-b738-9b4f359cb849"),
                            Content = "Last but not least, this gotcha!",
                            CreationDate = new DateTime(2023, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3456),
                            RepostQnt = 0,
                            UserId = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29")
                        });
                });

            modelBuilder.Entity("Domain.Gotcha.Repost.Entity.RepostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RepostDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Repost");
                });

            modelBuilder.Entity("Domain.Users.Entity.UsersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostsDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cdf691d-db36-4f9d-b567-2173d8431354"),
                            Active = true,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2022, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3301),
                            Email = "john.doe@example.com",
                            ImgBase64 = "6cdf691d-db36-4f9d-b567-2173d8431354.jpg",
                            LastAccessDate = new DateTime(2024, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3318),
                            LastName = "Doe",
                            Name = "John",
                            Nickname = "johnny",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("fba74d07-310a-4e3a-b689-bb129fbe566f"),
                            Active = true,
                            BirthDate = new DateTime(1985, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3327),
                            Email = "jane.smith@example.com",
                            ImgBase64 = "fba74d07-310a-4e3a-b689-bb129fbe566f.jpg",
                            LastAccessDate = new DateTime(2024, 5, 26, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3328),
                            LastName = "Smith",
                            Name = "Jane",
                            Nickname = "janeS",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("0e3ee3ef-a250-436b-bae6-754e2685b18c"),
                            Active = true,
                            BirthDate = new DateTime(1992, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 11, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3334),
                            Email = "alice.johnson@example.com",
                            ImgBase64 = "0e3ee3ef-a250-436b-bae6-754e2685b18c.jpg",
                            LastAccessDate = new DateTime(2024, 4, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3337),
                            LastName = "Johnson",
                            Name = "Alice",
                            Nickname = "aliceJ",
                            PostsDay = 0
                        },
                        new
                        {
                            Id = new Guid("b09a4ec4-0cea-45fb-b992-a94208837d29"),
                            Active = true,
                            BirthDate = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2021, 5, 27, 17, 36, 51, 76, DateTimeKind.Local).AddTicks(3340),
                            Email = "bob.brown@example.com",
                            ImgBase64 = "b09a4ec4-0cea-45fb-b992-a94208837d29.jpg",
                            LastAccessDate = new DateTime(2024, 5, 27, 12, 36, 51, 76, DateTimeKind.Local).AddTicks(3342),
                            LastName = "Brown",
                            Name = "Bob",
                            Nickname = "bobby",
                            PostsDay = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
